### ISSUE TITLE
Steps to actually run the compiled kaleidoscope binary

### ISSUE THREAD

**Issue by mhanberg** [acolite-d/llvm-tutorial-in-rust#1]
What are the steps to actually run the compiled file?

Running `cargo run test.ks` and then `./a.out` results in `zsh: exec format error: ./a.out` for me.

Thanks!

**Comment by acolite-d** [comment]
Hi @mhanberg!

This compiler can only produce object/assembly files, not executables. You will need to link with your runtime and define entrypoints in order to turn this into a runnable executable, which was not part of the original LLVM tutorial IIRC. Executing code will require the interpreted session.

Also, be sure to use `--` followed by the arguments to pass to your built binary, ex. `cargo r -- --help` or `cargo r -- test.ks`.

**Comment by acolite-d** [comment]
Actually, instead of linking with runtime and defining entrypoints, it might be easier to feed the resulting object into a C compiler of your choice, or rustc and run functions like so:



```C
// test.c
#include <stdio.h>

extern double fib(double);
extern double fibi(double);

int main(void) {
    printf("The 20th fibonacci number is: %.0lf\n", fibi(20));
    return 0;
}
```

```sh
clang test.c a.out -o test 
kaleidrs$ ./test
The 20th fibonacci number is: 6765
```

**Comment by mhanberg** [comment]
Compiling the following rust file

```rust
extern "C" {
    fn fibi(n: f64) -> f64;
}

fn main() {
    unsafe {
        println!("The 20th fibonacci number is: {:.0}", fibi(20.0));
    }
}
```

with rustc `rustc ks.rs -C link-args=./a.out` produces a `ks` binary that runs and outputs the correct value.

Thanks for the help!
